matrix:
  include:
    - os: linux
      language: node_js
      node_js: 15
      dist: trusty
      sudo: required
      addons:
        chrome: stable

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    fi
  - npm i -g yarn

install:
  - yarn install --network-timeout 1000000 # Timeout needed for Windows (really slow)
script:
  - yarn test
  # - yarn e2e
  # - yarn checkcommit
  # - yarn checkimports
  # - yarn documentation

addons:
  chrome: stable
cache:
  directories:
    - node_modules
notifications:
  email: false
  webhooks:
    on_success: true
    on_failure: true
    on_start: true