FROM ubuntu

# RUN apt-get update && apt-get -y install sudo curl
# RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
# USER docker

WORKDIR '/app'

COPY . .

# RUN pwd
# RUN ls -la

RUN chmod +x ./*.sh && chmod +x ./scripts/*.sh
RUN ./docker-npm-setup.sh

CMD ["/bin/sh", "./docker-run-tests.sh"]